"""schema7

Revision ID: 1dd2456be4b7
Revises: 
Create Date: 2026-04-08 22:28:59.493276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd2456be4b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_id'), 'admin_logs', ['id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=30), nullable=True),
    sa.Column('course_code', sa.String(length=30), nullable=True),
    sa.Column('course_name', sa.String(length=300), nullable=True),
    sa.Column('faculty_id', sa.String(length=30), nullable=True),
    sa.Column('faculty_name', sa.String(length=200), nullable=True),
    sa.Column('lecture_date', sa.String(length=50), nullable=True),
    sa.Column('timing', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_table('barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('availability_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcodes_barcode'), 'barcodes', ['barcode'], unique=True)
    op.create_index(op.f('ix_barcodes_id'), 'barcodes', ['id'], unique=False)
    op.create_table('cafe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('availability_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemid')
    )
    op.create_index(op.f('ix_cafe_items_id'), 'cafe_items', ['id'], unique=False)
    op.create_table('career_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.String(length=50), nullable=True),
    sa.Column('career_objective', sa.String(length=500), nullable=False),
    sa.Column('specialization_focus', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_skills', sa.Text(), nullable=True),
    sa.Column('preferred_learning_mode', sa.String(length=100), nullable=True),
    sa.Column('growth_index', sa.Float(), nullable=True),
    sa.Column('related_roles', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id')
    )
    op.create_index(op.f('ix_career_objectives_id'), 'career_objectives', ['id'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clubid', sa.String(length=50), nullable=True),
    sa.Column('club_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clubid')
    )
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=30), nullable=False),
    sa.Column('course_name', sa.String(length=300), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('l_t_p', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.String(length=50), nullable=True),
    sa.Column('event_name', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventid')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facultyid', sa.String(length=30), nullable=False),
    sa.Column('faculty_name', sa.String(length=200), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facultyid')
    )
    op.create_index(op.f('ix_faculty_id'), 'faculty', ['id'], unique=False)
    op.create_table('hackathons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackathon_id', sa.String(length=50), nullable=True),
    sa.Column('hackathon_name', sa.String(length=500), nullable=False),
    sa.Column('organizer', sa.String(length=300), nullable=True),
    sa.Column('registration_deadline', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('recommended_for', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id')
    )
    op.create_index(op.f('ix_hackathons_id'), 'hackathons', ['id'], unique=False)
    op.create_table('iro_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_iro', sa.Text(), nullable=True),
    sa.Column('main_objectives', sa.Text(), nullable=True),
    sa.Column('global_partners', sa.Text(), nullable=True),
    sa.Column('global_learning_pathways', sa.Text(), nullable=True),
    sa.Column('faqs', sa.Text(), nullable=True),
    sa.Column('student_testimonials', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('campus_connection', sa.Text(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iro_content_id'), 'iro_content', ['id'], unique=False)
    op.create_table('issued_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('roll_no', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issued_books_id'), 'issued_books', ['id'], unique=False)
    op.create_table('keyword_specialization_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('game_tech', sa.Float(), nullable=True),
    sa.Column('full_stack', sa.Float(), nullable=True),
    sa.Column('cyber_security', sa.Float(), nullable=True),
    sa.Column('data_science', sa.Float(), nullable=True),
    sa.Column('ai_ml', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_index(op.f('ix_keyword_specialization_map_id'), 'keyword_specialization_map', ['id'], unique=False)
    op.create_table('master_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('unique_key', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('editionstatement', sa.String(length=200), nullable=True),
    sa.Column('publishercode', sa.String(length=200), nullable=True),
    sa.Column('copyrightdate', sa.String(length=50), nullable=True),
    sa.Column('itemcallnumber', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('category_keyword', sa.String(length=200), nullable=True),
    sa.Column('cluster_label', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_books_book_id'), 'master_books', ['book_id'], unique=True)
    op.create_index(op.f('ix_master_books_id'), 'master_books', ['id'], unique=False)
    op.create_table('module_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_name')
    )
    op.create_index(op.f('ix_module_configs_id'), 'module_configs', ['id'], unique=False)
    op.create_table('open_electives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.Integer(), nullable=True),
    sa.Column('offered_by', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('course', sa.String(length=300), nullable=False),
    sa.Column('l_t_p', sa.String(length=20), nullable=True),
    sa.Column('vacancy', sa.String(length=100), nullable=True),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.Column('course_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_electives_id'), 'open_electives', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('roll_no', sa.String(length=30), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('sub_group', sa.String(length=20), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('career_objective', sa.String(length=500), nullable=True),
    sa.Column('technical_skills', sa.String(length=500), nullable=True),
    sa.Column('soft_skills', sa.String(length=500), nullable=True),
    sa.Column('personal_skills', sa.String(length=500), nullable=True),
    sa.Column('fav_cafe_item', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=True)
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.String(length=50), nullable=True),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('room_no', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('course_code', sa.String(length=30), nullable=True),
    sa.Column('faculty_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_index(op.f('ix_timetable_id'), 'timetable', ['id'], unique=False)
    op.create_table('lost_found_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location_found', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_approved', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_found_items_id'), 'lost_found_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lost_found_items_id'), table_name='lost_found_items')
    op.drop_table('lost_found_items')
    op.drop_index(op.f('ix_timetable_id'), table_name='timetable')
    op.drop_table('timetable')
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_open_electives_id'), table_name='open_electives')
    op.drop_table('open_electives')
    op.drop_index(op.f('ix_module_configs_id'), table_name='module_configs')
    op.drop_table('module_configs')
    op.drop_index(op.f('ix_master_books_id'), table_name='master_books')
    op.drop_index(op.f('ix_master_books_book_id'), table_name='master_books')
    op.drop_table('master_books')
    op.drop_index(op.f('ix_keyword_specialization_map_id'), table_name='keyword_specialization_map')
    op.drop_table('keyword_specialization_map')
    op.drop_index(op.f('ix_issued_books_id'), table_name='issued_books')
    op.drop_table('issued_books')
    op.drop_index(op.f('ix_iro_content_id'), table_name='iro_content')
    op.drop_table('iro_content')
    op.drop_index(op.f('ix_hackathons_id'), table_name='hackathons')
    op.drop_table('hackathons')
    op.drop_index(op.f('ix_faculty_id'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_career_objectives_id'), table_name='career_objectives')
    op.drop_table('career_objectives')
    op.drop_index(op.f('ix_cafe_items_id'), table_name='cafe_items')
    op.drop_table('cafe_items')
    op.drop_index(op.f('ix_barcodes_id'), table_name='barcodes')
    op.drop_index(op.f('ix_barcodes_barcode'), table_name='barcodes')
    op.drop_table('barcodes')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_admin_logs_id'), table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
